/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yangyr17_v4o6_JNIUtils */

#ifndef _Included_com_yangyr17_v4o6_JNIUtils
#define _Included_com_yangyr17_v4o6_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yangyr17_v4o6_JNIUtils
 * Method:    startBackend
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yangyr17_v4o6_JNIUtils_startBackend
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
